<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akunp_model extends CI_Model
{

    public $table = 't04_akunp';
    public $id = 'idakun';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database($this->session->userdata('groupName'), true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idakun', $q);
    	$this->db->or_like('Kode', $q);
    	$this->db->or_like('Nama', $q);
    	$this->db->or_like('Induk', $q);
    	$this->db->or_like('Urut', $q);
    	$this->db->or_like('created_at', $q);
    	$this->db->or_like('updated_at', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idakun', $q);
    	$this->db->or_like('Kode', $q);
    	$this->db->or_like('Nama', $q);
    	$this->db->or_like('Induk', $q);
    	$this->db->or_like('Urut', $q);
    	$this->db->or_like('created_at', $q);
    	$this->db->or_like('updated_at', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /**
     * modif
     */
    function getById($id)
    {
        $this->db->where('induk', $id);
        return $this->db->get($this->table)->row();
    }

    /**
     * get new kode-sub by kode-induk
     */
    function getNewKode($induk, $kodeInduk)
    {
        $row = $this->getById($induk);
        if ($row) {
            $value = $row->Kode;
            $sLastKode = intval(substr($value, 10, 3)); // ambil 3 digit terakhir
            $sLastKode = intval($sLastKode) + 1; // konversi ke integer, lalu tambahkan satu
            $sNextKode = substr($value, 0, 10) . sprintf('%03s', $sLastKode); // format hasilnya dan tambahkan prefix
        } else {
            /**
             * data yang dicari :: tidak ditemukan, maka
             * kode-induk + 1   => untuk level 2
             *            + 01  => untuk level 3
             *            + 001 = > untuk level 4 dan 5
             */
            $sNextKode = $kodeInduk . '001';
        }
        return $sNextKode;
    }

}

/* End of file Akunp_model.php */
/* Location: ./application/models/Akunp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-10-12 15:51:36 */
/* http://harviacode.com */
