<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sa_model extends CI_Model
{

    public $table = 'v03_sa';
    public $id = 'idsa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database($this->session->userdata('groupName'), true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        // $this->db->like('', $q);
    	$this->db->or_like('idsa', $q);
    	$this->db->or_like('idakun', $q);
    	$this->db->or_like('Debit', $q);
    	$this->db->or_like('Kredit', $q);
    	$this->db->or_like('c', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        // $this->db->like('', $q);
    	$this->db->or_like('idsa', $q);
    	$this->db->or_like('idakun', $q);
    	$this->db->or_like('Debit', $q);
    	$this->db->or_like('Kredit', $q);
    	$this->db->or_like('c', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /**
     * modif
     * join ke t02_akun
     */
    function getLimitData($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->table . '.idakun', 'asc');
        // $this->db->like('', $q);
    	$this->db->or_like('idsa', $q);
    	$this->db->or_like($this->table . '.idakun', $q);
    	$this->db->or_like('Debit', $q);
    	$this->db->or_like('Kredit', $q);
    	$this->db->or_like('c', $q);
    	$this->db->limit($limit, $start);
        // $this->db->select($this->table . '.*, t02_akun.Kode, t02_akun.Nama');
        $this->db->select($this->table . '.*, v02_klasak2.Kode, v02_klasak2.Nama');
        $this->db->from($this->table);
        // $this->db->join('t02_akun', 't02_akun.idakun = '.$this->table.'.idakun');
        $this->db->join('v02_klasak2', 'v02_klasak2.idakun = '.$this->table.'.idakun');
        return $this->db->get()->result();
    }

    /**
     * cari klasak level terakhir versi 2
     * untuk gabungan akun buku besar dan akun buku pembantu
     * buku besar => idakun = idakun
     * buku pembantu => idakun = 1000 + induk + idsa
     */
    function getAllLastLevel()
    {
        $this->db->where('idakun not in (select induk from v02_klasak2)');
        $this->db->order_by('Urut', 'asc');
        return $this->db->get('v02_klasak2')->result();
    }

}

/* End of file Sa_model.php */
/* Location: ./application/models/Sa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-10-13 11:22:02 */
/* http://harviacode.com */
