<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bukubesar_model extends CI_Model
{

    public $table = 'v02_bukubesar';
    public $id = 'idakun';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database($this->session->userdata('groupName'), true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
    	$this->db->or_like('idakun', $q);
    	$this->db->or_like('Kode', $q);
    	$this->db->or_like('Nama', $q);
    	$this->db->or_like('Induk', $q);
    	$this->db->or_like('Urut', $q);
    	$this->db->or_like('Debit', $q);
    	$this->db->or_like('Kredit', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
    	$this->db->or_like('idakun', $q);
    	$this->db->or_like('Kode', $q);
    	$this->db->or_like('Nama', $q);
    	$this->db->or_like('Induk', $q);
    	$this->db->or_like('Urut', $q);
    	$this->db->or_like('Debit', $q);
    	$this->db->or_like('Kredit', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /**
     * modif
     */
    function getAllAkun()
    {
        $this->db->order_by('Urut', 'asc');
        return $this->db->get($this->table)->result();
    }

    /**
     * modif show data buku besar
     */
    function getById($id)
    {
        $this->db->where($this->id, $id);
        // $r = $this->db->get($this->table)->row(); echo pre($this->db->last_query()); die();
        return $this->db->get($this->table)->row();
    }

}

/* End of file Bukubesar_model.php */
/* Location: ./application/models/Bukubesar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-10-08 08:36:32 */
/* http://harviacode.com */
