<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Package_model extends CI_Model
{

    public $table = 't01_package';
    public $id = 'idprice';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database('tamu', true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idprice', $q);
	$this->db->or_like('PackageName', $q);
	$this->db->or_like('PackageCode', $q);
	$this->db->or_like('SN3LN', $q);
	$this->db->or_like('SN6LN', $q);
	$this->db->or_like('SNELN', $q);
	$this->db->or_like('PN1LN', $q);
	$this->db->or_like('PN1DN', $q);
	$this->db->or_like('SN3C', $q);
	$this->db->or_like('SN3CP', $q);
	$this->db->or_like('SN6C', $q);
	$this->db->or_like('SN6CP', $q);
	$this->db->or_like('SNEC', $q);
	$this->db->or_like('SNECP', $q);
	$this->db->or_like('PN3C', $q);
	$this->db->or_like('PN3CP', $q);
	$this->db->or_like('PN6C', $q);
	$this->db->or_like('PN6CP', $q);
	$this->db->or_like('PNEC', $q);
	$this->db->or_like('PNECP', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idprice', $q);
	$this->db->or_like('PackageName', $q);
	$this->db->or_like('PackageCode', $q);
	$this->db->or_like('SN3LN', $q);
	$this->db->or_like('SN6LN', $q);
	$this->db->or_like('SNELN', $q);
	$this->db->or_like('PN1LN', $q);
	$this->db->or_like('PN1DN', $q);
	$this->db->or_like('SN3C', $q);
	$this->db->or_like('SN3CP', $q);
	$this->db->or_like('SN6C', $q);
	$this->db->or_like('SN6CP', $q);
	$this->db->or_like('SNEC', $q);
	$this->db->or_like('SNECP', $q);
	$this->db->or_like('PN3C', $q);
	$this->db->or_like('PN3CP', $q);
	$this->db->or_like('PN6C', $q);
	$this->db->or_like('PN6CP', $q);
	$this->db->or_like('PNEC', $q);
	$this->db->or_like('PNECP', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Package_model.php */
/* Location: ./application/models/Package_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-10-08 05:42:04 */
/* http://harviacode.com */
